### ISSUE TITLE
I want to connect withtidalcycles 

### ISSUE THREAD

**Issue by NishizawaKazuhiro** [fand/veda#105]
I want to connect with tidalcycles and veda now.It was already realized in MacOS and win32.(See this link https://youtu.be/kjC2QEZQa_Y)
But this sorce code didn't work well in my computer environment.
My computer environment is win64 ver 10.
If you know the solution,please give me some comment.

**Comment by fand** [comment]
The system looks a bit complicated as it works by sending messages like: 
`TidalCycles -> SuperCollider -> (OSC) -> VEDA` 

We should check each connection is working correctly.

1. Check OSC messages sent from SuperCollider with OSC receivers like TouchDesigner or [oscer](https://github.com/aike/oscer).
2. Check if VEDA receives OSC signals using oscer etc.

**Comment by NishizawaKazuhiro** [comment]
When I reboot my PC, this setting seems to work well.
Thank you your advice.
