### ISSUE TITLE
cannot install veda atom package

### ISSUE THREAD

**Issue by BrandonLSW** [fand/veda#118]
Hi, 
When running in this command, it stuck on this status for a long time and got no response (Same installed in the Atom Editor). It seems that it was running npm command. 
BrandontekiMacBook-Pro:packages brandon$ apm install veda
Installing veda to /Users/brandon/.atom/packages 

Python Version: Python 2.7.10
And Already installed glslangValidator

How can I resolve this issue? Thanks!

**Comment by fand** [comment]
Hi @BrandonLSW ! Thank you for checking out VEDA.

It occasionally takes long to install VEDA (I'm not sure why... maybe it's because some big dependencies like Three.js)...
However, it'll be installed correctly after 3~4 minutes. 
Could you try it again?

**Comment by BrandonLSW** [comment]
Hi @fand , Thank you for your response. 
<img width="929" alt="sc" src="https://user-images.githubusercontent.com/47446095/52477723-ea4a1080-2bdd-11e9-968b-d96fdfac6134.png">
It seems that I finally got VEDA installed, but it prompted me "No projects found in this window" when I toggled it. Is there anything I am missing?

**Comment by fand** [comment]
To run VEDA, Atom has to be opened on a specific directory, not a single file so that it can load other resources such as videos, node modules, etc.
Please try following steps:

1. Open a directory on Atom
2. Enable VEDA
3. Save

**Comment by BrandonLSW** [comment]
Hi @fand , it works. Thanks!
