### ISSUE TITLE
Server mode not refreshing

### ISSUE THREAD

**Issue by jpupper** [fand/veda#126]
So, i´ve recently started using VEDA.

I can´t seem to be able to refresh the shader onces is been launched to the server.

This is my code, as you can see is almost as the example : 

```
`/*
  {"server":3000}
*/

precision mediump float;
uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;


void main(void) {
  vec2 uv = gl_FragCoord.xy / resolution.xy;
  
  gl_FragColor = vec4(0.0,0.0,0.9, 1.0);
}
`
```

The server opens one time. and then it can´t be refreshed. 

I´ve already tryed in : opera, chrome, firefox with same result

If i changed the server address then it start to broadcast the shader to other server adress, the shader appears right.

It seems like it can´t refresh the server once is created. 

Is there any way to force server update? Im not an expert on node.js but it is supposed to auto-update once the shader is change right? 

Thanks for reading.
Look forward to hearing from you.

**Comment by fand** [comment]
Fixed in v2.11.4. Thank you for reporting! @Aurelian24 😸
