### ISSUE TITLE
Transparency / alpha on font background, and the font itself

### ISSUE THREAD

**Issue by semsion** [fand/veda#129]
Hopefully these questions can be answered here, please advise where otherwise.

Is transparency on the font background, and the font itself possible with the current setup of Veda in Atom?

Also, can you have Veda running in the background, and do development on other projects with the visuals running simultaneously?

**Comment by fand** [comment]
Hi @itsopen ! 

> Is transparency on the font background, and the font itself possible with the current setup of Veda in Atom?

VEDA doesn't provide a way to change the background/foreground color of text.
The color is hard coded.

https://github.com/fand/veda/blob/master/styles/veda.less#L40

If you wanna change the color though, you can edit the stylesheet in the directory VEDA is installed in your PC.   
If you're using macOS, the stylesheet is in `~/.atom/packages/veda/styles/veda.less`.

> Also, can you have Veda running in the background, and do development on other projects with the visuals running simultaneously?

When multiple projects are opened in Atom, VEDA recognizes the first project as the project to run shaders. like  this:

- Run VEDA
- Add projects by `Add Project Folder`
- Do development as you want

**Comment by semsion** [comment]
Wonderful, thank you ...
