### ISSUE TITLE
Nested Loop make the pixel pass crash =>

### ISSUE THREAD

**Issue by MsieurTempeteBitch** [fand/veda#140]
I have a simple *.frag file i wanna make work.

If I nest a loop, for example :
void main() {

gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);

  for(int i = 0; i < 10; i++){
    for(j = 0; j < 10; j++)
    {
    }
  }
}

the pixel pass crash and the screen remains black.

**Comment by fand** [comment]
Hi @MsieurTempeteBitch !
Is that the actual code you tried?
If so, `j` must be declared like `for (int j = 0;`, otherwise it fails to compile.

**Comment by MsieurTempeteBitch** [comment]
Hey,

No it's not the code I've made, I just put a example code.

Of course it was initialized, even with a while loop

Can you nest loop ?

If you can maybe the problem is somewhere else...

Thx !

**Comment by fand** [comment]
Sorry that i've completely forgot about this issue...
I tried using nested loops and it worked without problems. 
https://gist.github.com/fand/8c5a31eb544b35f2eb489c4fda8dea5d
