### ISSUE TITLE
audio input linux

### ISSUE THREAD

**Issue by Kame7C0** [fand/veda#16]
system: Ubuntu 17.04 using ALSA

I cant get example 'audio.frag' to work...
I imagine it suppose to use Input Device witch is set to monitoring, so I can use what I hear.
![audio_setup](https://user-images.githubusercontent.com/3462746/30239278-22f0a074-9559-11e7-8aa1-192a301a1ddf.png)

tested with VSXu and it works fine, (I can see audio) - vsxu.com
...so any tips how to get audio would be great.

P.S. Just found this nice package by accident and its a lot of fun. THX.

**Comment by fand** [comment]
Thank you for reporting, @CezaryKopias !

I've not tested on Linux, but it seems it uses the monitoring device.
In current implementation, glsl-livecoder uses 1st audio input.
I don't understand how your devices are organized... maybe turning off monitoring mode will help you.👍

**Comment by Kame7C0** [comment]
hmmm...
after some testing i get it to work
i have 3 sound cards = 2 sound blaster`s + graphics card nvidia hdmi
and this issue is occurring only when i use nvidias hdmi
if i find solution i will post it here... bug closed

P.S. would be really nice if you could link some glsl learning material...  after googling I`m rather confused where to start... but maybe looking at examples is the best way :D

**Comment by Kame7C0** [comment]
ugh.. 
updated from 0.8.1 that worked like posted... 
to 0.9.1 and its broken on all sound cards...

**Comment by Kame7C0** [comment]
reverting...
`apm install glsl-livecoder@0.8.1`
let me know when to update and test...

**Comment by fand** [comment]
ah, there is a breaking change. 😖
`audio` diabled by default after `v0.9.0`.
Please try putting `/*{ "audio": true }*/` on the 1st line of the source code or `.liverc` like this: https://github.com/fand/glsl-livecoder#project-settings-liverc

> glsl learning material

I recommend this book as the starting point. 
https://thebookofshaders.com/

maybe i should add links for learning materials to README..

**Comment by Kame7C0** [comment]
All Good.
Thx for link.
