### ISSUE TITLE
Support OSC

### ISSUE THREAD

**Issue by fand** [fand/veda#18]
OSC is a widely-used protocol like MIDI, but more flexible.
I'm not familiar with OSC. Comments welcome!

**Comment by fand** [comment]
TouchOSC + TouchOSC Bridge works as a normal MIDI device, so we can use it via `sampler2D midi`.

**Comment by fand** [comment]
Because OSC allows arbitrary addresses and data, it's difficult to map OSC events to textures...
I'm considering using just 1 address and 3 data mapped to 2D texuture, just like `sampler2D midi`.

**Comment by Mortec** [comment]
This would be a great feature !
This would make glsl-livecoder a good pal for [Supercollider](http://supercollider.github.io).
You coud ad a few predefined messages with special adresses, a few floats and a few float arrays as sampler2D  with fixed size could be a good start : 
/glsl-viewer/float0/ ...
/glsl-viewer/float1/ ...

/glsl-viewer/floatArray0/../......../../...
/glsl-viewer/floatArray1/../......../../...
etc...

**Comment by fand** [comment]
Supported in v2.0.0 🎉
