### ISSUE TITLE
Not able tu use ocs inputs into Veda

### ISSUE THREAD

**Issue by LouisCortes** [fand/veda#183]
Hello,

I don't know if I miss somthing, but nothingg happend when I try to send osc messages.
I put /*{ "osc": 4000 }*/ at the beginning of my fragment then I set a texture with osc_f7_f1 for a message wich is /f7/f1 and the texture remain black.

I'm using OscTouch with 4000 for outgoing port, the message are send on other softs but I can't get it work on Veda.

I also try to put  the line :  "osc": 4000 inside my .verdac and i tried all the example tat i found but I 'm still not able to get it working.

btw thanks for your work, I love it.

**Comment by LouisCortes** [comment]
I don't know if it's related but when I open the .frag with the OSC inputs I got that message that appear :  
![image](https://user-images.githubusercontent.com/43936968/81510850-5e112680-9315-11ea-9411-39776cd3d747.png)

It only apears when I have the OSC instruction in the file.

**Comment by fand** [comment]
ah yes, VEDA requires Node.js to run OSC server.
I added instructions to docs.

- https://veda.gl/install/
- https://veda.gl/faq/

Thanks @LouisCortes !

**Comment by LouisCortes** [comment]
It works directly, thanks !
