### ISSUE TITLE
vertex shader black screen

### ISSUE THREAD

**Issue by Kame7C0** [fand/veda#23]
tested on: Atom 1.20; glsl-livecoder 0.9.4 and 0.10.0; linux and windows
I tried to code some vertex shader and got only black (also tried with example).

0.8.1 works :smile:

**Comment by fand** [comment]
Thx for reporting!

It was a bug on initializing `vertexCount`.
fixed in https://github.com/fand/glsl-livecoder/commit/84a93e927e05ab430097d488dd12a3e2eabd9c4b and published v0.10.2. Please try it! @CezaryKopias

**Comment by Kame7C0** [comment]
thx
