### ISSUE TITLE
silly fetchPackageMetaData error for https://www.atom.io/api/packages/veda/versions/2.13.1/tarball zlib: unexpected end of file

### ISSUE THREAD

**Issue by daaaisuke** [fand/veda#235]
When I tried to install veda, An error is occured in below step and cant install veda.
> apm install veda

ERROR LOG():
`0 info it worked if it ends with ok↲
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',↲
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',↲
1 verbose cli   '--globalconfig',↲
1 verbose cli   '/Users/daisuke/.atom/.apm/.apmrc',↲
1 verbose cli   '--userconfig',↲
1 verbose cli   '/Users/daisuke/.atom/.apmrc',↲
1 verbose cli   'install',↲
1 verbose cli   'https://www.atom.io/api/packages/veda/versions/2.13.1/tarball',↲
1 verbose cli   '--target=4.2.7',↲
1 verbose cli   '--disturl=https://atom.io/download/electron',↲
1 verbose cli   '--arch=x64',↲
1 verbose cli   '--global-style' ]↲
2 info using npm@6.2.0↲
3 info using node@v10.2.1↲
4 verbose npm-session 76752d6db4f3c2c9↲
5 silly install loadCurrentTree↲
6 silly install readLocalPackageData↲
7 http fetch GET 304 https://www.atom.io/api/packages/veda/versions/2.13.1/tarball 2078ms (from cache)↲
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/veda/versions/2.13.1/tarball zlib: unexpected end of file↲
9 timing stage:rollbackFailedOptional Completed in 2ms↲
10 timing stage:runTopLevelLifecycles Completed in 2211ms↲
11 verbose stack ZlibError: zlib: unexpected end of file↲
11 verbose stack     at Zlib.(anonymous function).onerror (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:131:21)↲
11 verbose stack     at Unzip.write (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:255:31)↲
11 verbose stack     at Unzip.flush (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:222:10)↲
11 verbose stack     at Unzip.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:229:10)↲
11 verbose stack     at Object.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/tar/lib/parse.js:415:21)↲
11 verbose stack     at PassThrough.onend (_stream_readable.js:634:10)↲
11 verbose stack     at Object.onceWrapper (events.js:273:13)↲
11 verbose stack     at PassThrough.emit (events.js:187:15)↲
11 verbose stack     at endReadableNT (_stream_readable.js:1090:12)↲
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)↲
12 verbose cwd /private/var/folders/t7/rp47b_3508zf_xhqbqfk2cf80000gp/T/apm-install-dir-120319-45963-1jf88bx.5aph↲
13 verbose Darwin 17.7.0↲
14 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/daisuke/.atom/    .apm/.apmrc" "--userconfig" "/Users/daisuke/.atom/.apmrc" "install" "https://www.atom.io/api/packages/veda/versions/2.13.1/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--ar    ch=x64" "--global-style"↲
15 verbose node v10.2.1↲
16 verbose npm  v6.2.0↲
17 error code Z_BUF_ERROR↲
18 error errno -5↲
19 error zlib: unexpected end of file↲
20 verbose exit [ -5, true ]↲`

What's wrong??

**Comment by fand** [comment]
Hi @daaaisuke , sorry for late reply.

> silly fetchPackageMetaData error for https://www.atom.io/api/packages/veda/versions/2.13.1/tarball zlib: unexpected end of file

Hmm, it seems Atom failed to download the file for some reason (temporal network error etc).
Please restart Atom and re-install VEDA.
