### ISSUE TITLE
Can't declare an array

### ISSUE THREAD

**Issue by myxyy** [fand/veda#242]
I want to use array declaration like:

```float array[3] = float[3](1.0,0.0,1.0);```

but I get an error message:
>'arrayed constructor' : not supported for this version or the enabled extensions

Do I need some extensions or is there an alternative way to use an array-like structure?

**Comment by fand** [comment]
Hi @myxyy !
Unfortunately VEDA doesn't support constant arrays because it runs on WebGL 1, which only supports GLSL ES 2.0.
However,  you can use `vec3` instead of float arrays like: `vec3 array = (1.0, 0.0, 1.0);`.

**Comment by myxyy** [comment]
Thanks, I understand.
Practically, I want to use more longer array, of size 8 or 16, for sound shaders.
