### ISSUE TITLE
Black screen when trying video.frag

### ISSUE THREAD

**Issue by melas0nos** [fand/veda#243]
I get just a black screen when opening video.frag example.

This is a Dell G7 / Windows 10 / with integrated Intel UHD 630 graphics, and NVIDIA GTX 1060 with Max-Q

I have tried disabling NVIDIA, and setting atom to use integrated graphics in the NVIDIA control panel. I have also reinstalled the package, tried using "run as administrator" and running with atom --ingore-gpu-blacklist

I cant run other examples like mouse.frag

Here is the debug console in Atom:

C:\Users\TuCrow\AppData\Local\atom\app-1.48.0\resources\app.asar\src\text-editor-element.js:357 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
(anonymous) @ C:\Users\TuCrow\AppData\Local\atom\app-1.48.0\resources\app.asar\src\text-editor-element.js:357
C:\Users\TuCrow\.atom\packages\veda\lib\wrapper.js:12 {}
C:\Users\TuCrow\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:47283 THREE.JSONLoader has been removed.
JSONLoader @ C:\Users\TuCrow\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:47283
ModelLoader @ C:\Users\TuCrow\.atom\packages\veda\node_modules\vedajs\lib\model-loader.js:30
Veda @ C:\Users\TuCrow\.atom\packages\veda\node_modules\vedajs\lib\veda.js:131
Player @ C:\Users\TuCrow\.atom\packages\veda\lib\player.js:68
App @ C:\Users\TuCrow\.atom\packages\veda\lib\app.js:81
Wrapper @ C:\Users\TuCrow\.atom\packages\veda\lib\wrapper.js:22
_activate @ C:\Users\TuCrow\.atom\packages\veda\lib\index.js:89
(anonymous) @ C:\Users\TuCrow\.atom\packages\veda\lib\index.js:86
Promise.then (async)
activate @ C:\Users\TuCrow\.atom\packages\veda\lib\index.js:86
activateNow @ <embedded>:11
(anonymous) @ <embedded>:14
simpleDispatch @ <embedded>:11
emit @ <embedded>:11
handleCommandEvent @ <embedded>:11
didConfirmSelection @ <embedded>:11
confirmSelection @ <embedded>:11
core:confirm @ <embedded>:11
handleCommandEvent @ <embedded>:11
KeymapManager.dispatchCommandEvent @ <embedded>:11
KeymapManager.handleKeyboardEvent @ <embedded>:11
handleDocumentKeyEvent @ <embedded>:11
C:\Users\TuCrow\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:22137 THREE.WebGLRenderer 100
C:\Users\TuCrow\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:22137 THREE.WebGLRenderer 100
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:15 Update config {glslangValidatorPath: "", IMPORTED: {…}, PASSES: Array(0), pixelRatio: 2, frameskip: 2, …}
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:142 [VEDA] Updated shader [{…}]
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:15 Update config {glslangValidatorPath: "", IMPORTED: {…}, PASSES: Array(0), pixelRatio: 2, frameskip: 2, …}
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:142 [VEDA] Updated shader [{…}]
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:15 Update config {glslangValidatorPath: "", IMPORTED: {…}, PASSES: Array(0), pixelRatio: 2, frameskip: 2, …}
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:142 [VEDA] Updated shader [{…}]
C:\Users\TuCrow\.atom\packages\veda\lib\config.js:99 [VEDA] config file not found
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:15 Update config {glslangValidatorPath: "", IMPORTED: {…}, PASSES: Array(0), pixelRatio: 2, frameskip: 2, …}IMPORTED: {}PASSES: [{…}]audio: falsecamera: falsefftSize: 2048fftSmoothingTimeConstant: 0.8frameskip: 2gamepad: falseglslangValidatorPath: ""glslify: falsekeyboard: falsemidi: falseosc: nullpixelRatio: 2server: nullsoundLength: 30vertexCount: 3000vertexMode: "LINE_STRIP"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:142 [VEDA] Updated shader [{…}]0: {MODEL: undefined, TARGET: undefined, FLOAT: undefined, WIDTH: undefined, HEIGHT: undefined, …}length: 1__proto__: Array(0)
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:15 Update config {glslangValidatorPath: "", IMPORTED: {…}, PASSES: Array(0), pixelRatio: 2, frameskip: 2, …}
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:142 [VEDA] Updated shader [{…}]
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:15 Update config {glslangValidatorPath: "", IMPORTED: {…}, PASSES: Array(0), pixelRatio: 2, frameskip: 2, …}
C:\Users\TuCrow\.atom\packages\veda\lib\player.js:142 [VEDA] Updated shader [{…}]

**Comment by fand** [comment]
Hi @kelleytheisen7 ! sorry for late reply.

The error messages is not relevant to the problem AFAIK, and `video.frag` still works on my PCs (I tried both win & mac).
Can you try the solutions in [FAQ](https://veda.gl/faq/) ?
