### ISSUE TITLE
Not working here.

### ISSUE THREAD

**Issue by Mortec** [fand/veda#27]
Well I tried several installation following your instruction but nothing happen here.
I`m on El Capitan 10.11.6, glslang 3.0 is installed and I try to run glsl-livecoder with Atom 1.20. I have also the linter packages dependency but nothing happens when I  open your examples and try to load and watch the shaders wether I toggle glsl-livecoder or not.
Did I miss something?

**Comment by fand** [comment]
hmm... maybe you have to run `Rebuild packages`.
Please follow this article and try it.
https://medium.com/@amagitakayosi/vj-live-coding-on-atom-glsl-livecoder-329eec5462df#732d

If it doesn't help you, please show me the error messages on DevTools.
DevTools can be opened from here:
![graph](https://user-images.githubusercontent.com/1403842/30791496-cfe8aaec-a1ed-11e7-8ff1-50c337473b4d.png)

thx 🐱  @Mortec

**Comment by Mortec** [comment]
Yes I had this little "bug" and did the rebuilding, apparently everything is in place but I have this error messages in the console of DevTools : 

THREE.WebGLRenderer 86
/Users/mortec/.atom/packages/glsl-livecoder/node_modules/three/build/three.js:20522 THREE.WebGLRenderer: Error creating WebGL context.
WebGLRenderer @ /Users/mortec/.atom/packages/glsl-livecoder/node_modules/three/build/three.js:20522
/Users/mortec/.atom/packages/glsl-livecoder/node_modules/three/build/three.js:20096 Uncaught (in promise) TypeError: Cannot read property 'getExtension' of null
    at Object.get (/Users/mortec/.atom/packages/glsl-livecoder/node_modules/three/build/three.js:20096:21)
    at new WebGLRenderer (/Users/mortec/.atom/packages/glsl-livecoder/node_modules/three/build/three.js:20528:14)
    at ThreeShader.setCanvas (/Users/mortec/.atom/packages/glsl-livecoder/lib/three-shader.js:116:22)
    at new GlslLivecoder (/Users/mortec/.atom/packages/glsl-livecoder/lib/glsl-livecoder.js:51:17)
    at Object._activate (/Users/mortec/.atom/packages/glsl-livecoder/lib/index.js:82:16)
    at /Users/mortec/.atom/packages/glsl-livecoder/lib/index.js:67:24

**Comment by fand** [comment]
I found many people encountered the same problem, but the fix is not found yet 😖
https://github.com/mrdoob/three.js/issues/4927

I'm on macOS 10.12.6 & Atom v1.20.1, and there's no errors.
Upgrading macOS or Atom might fix it...??

Sorry I can't fix it. I'll keep on looking for the solution 😿

**Comment by Mortec** [comment]
Hey,

Apparently Atom is based on Chromium whom the staff has decided last year to blacklist some GPUs.
That's why it couldn't create the context. I'm on a Macbook 2011 and I have an integrated Intel HD3000 GPU which is on the black list but this should concern some other GPUs..

To solve the issue one must disable the blacklist in the start.js of Atom located here on my machine : 
/Applications/Atom.app/Contents/Resources/app/src/main-process/start.js

Simply add this line just before the line ~32 ("const args = parseCommandLine(process.argv.slice(1))" ) : 

`app.commandLine.appendSwitch('ignore-gpu-blacklist')`

I found the trick thanks to this two threads : 
https://discuss.atom.io/t/is-atom-able-to-use-the-gpu/46849/2
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-reviews/I6dL_9IAwiE

You'll see the second discussion on the google group is very funny !

Your glsl-livecoder seems great, can't wait for the OSC communication.

**Comment by fand** [comment]
Thank you for the information!
so I have to buy a new macbook for my father, who loves killing time on Street View... 😹 

I'm gonna add the workaround to README. 

Currently I'm working on deferred rendering / multipath rendering feature.
After that I'll try OSC, so don't miss it!
