### ISSUE TITLE
"Unable to locate glslangValidator at 'glslangValidator'" when I try to load shader

### ISSUE THREAD

**Issue by entyo** [fand/veda#31]
I can use `toggle` feature :+1: 

But, then, running `load-shader` / `watch-shader` to load another `.frag`, I got an error.  

```Unable to locate glslangValidator at 'glslangValidator'```

![screenshot from 2017-10-13 09-47-53](https://user-images.githubusercontent.com/6816182/31525490-a0600236-affb-11e7-98a7-e617258f3aa6.png)

**Comment by fand** [comment]
Hm,,,seems that it fails to resolve the path of glslangValidator.
Setting `glslangValidator` path manually will fix the error. ( e.g. `/use/local/bin/glslangValidator`)

**Comment by entyo** [comment]
@fand You are right! I fixed this by `mv /home/entyo/VulkanSDK/1.0.61.1/x86_64/bin/glslangValidator /usr/local/bin` :smile:

**Comment by demicuz** [comment]
I have the same issue. Setting the path to `C:\VulkanSDK\1.0.65.1\Bin` doesn't help. It has `glslangValidator.exe` in it, the folder also added to `PATH`. Am I doing something wrong?

UPD: `C:\VulkanSDK\1.0.65.1\Bin\glslangValidator.exe` worked.

**Comment by tgsoon2002** [comment]
hi there, where can I find path on mac?

**Comment by mbncr** [comment]
Don't know if it has to do with more recent version of VulkanSDK, but the one in `C:\VulkanSDK\1.1.92.1\Bin32\glslangValidator.exe` was the one that worked for me.
