### ISSUE TITLE
WebGL2

### ISSUE THREAD

**Issue by fand** [fand/veda#45]
VEDA is built on Three.js now.
There is an issue for WebGL2Renderer but it seems to be diffucult 😇 
https://github.com/mrdoob/three.js/issues/9965

Babylon.js already supports WebGL.
https://www.babylonjs.com/

Should we wait for THREE.WebGL2Renderer, or migrate to Babylon.js...?

**Comment by AlexandreRangel** [comment]
Stick to Three.js ;)

**Comment by fand** [comment]
close until Three.js supports webgl2 😸
