### ISSUE TITLE
Hearing audio feedback whenever glsl-livecoder is toggled on

### ISSUE THREAD

**Issue by glastonbridge** [fand/veda#5]
When I load up Atom I experience no audio feedback. As soon as I click Packages->glsl_livecoder->Toggle, I hear audio feedback (echoing and a shrill whine) from the speaker to the microphone. I understand that the audio input API must read the microphone input, but surely it does not need to output the same audio to the speaker.

Using glsl-livecoder 0.4.1 on OSX with Atom 1.18.0 64 bit.

**Comment by fand** [comment]
Yeah it's a bug...I forgot to mute audio output.
fixed in https://github.com/fand/glsl-livecoder/commit/3e72dada9b9eee3fb255c2d591e8ee6b24448a09 and published v0.4.2.
Please try it! @glastonbridge

**Comment by fand** [comment]
Please reopen If the bug still reproduces.

**Comment by glastonbridge** [comment]
Seems to be working just fine now, thank you @fand !
