### ISSUE TITLE
Blank lines slow down compilation dramatically

### ISSUE THREAD

**Issue by demicuz** [fand/veda#57]
[Fragment shader gist](https://gist.github.com/demicuz/c120cf68020f3c9b36016c513ece908a) with this issue being present. On my laptop it takes >20 sec to compile. And [this](https://gist.github.com/demicuz/08b5b40df6c613a7a1ed75b91a0d691b) is exactly the same shader, comments removed, which compiles instantly.

Also, it seems like you can't have `/*...*/` comments anywhere in your code, as it ruins commands such as `/*{server:3000}*/`.

**Comment by demicuz** [comment]
Interestingly, [replacing commented code with dummy text](https://gist.github.com/demicuz/533e004dd1658203608cc9bba984f0bc) helped a bit. Now compilation time is about 10 sec.

**Comment by Chovin** [comment]
time to make an esoteric comment language so you can comment in VEDA :+1:

**Comment by fand** [comment]
@demicuz 
Thx for reporting!

The shader compiles in about .5 sec in my environment... (MBP 2013)
What's your environment?

The 2nd bug is fixed in v2.4.2. Plz try this 🙏

**Comment by demicuz** [comment]
I've experimented a bit with the code, and it seems that the issue is caused by blank lines in a shader. On my laptop I start noticing it after 21 blank lines (takes about 2 sec), but 18 is totally OK. With 26 it runs in about 35 sec. Their location doesn't matter, it's the overall number of them that slows things down. Try running [this shader with 30 blank lines](https://pastebin.com/H9jNsH3S).

**Comment by demicuz** [comment]
I've updated VEDA to 2.4.2 and the issue is gone. It seems like 8d19883 fixed all this weird behaviour.

**Comment by fand** [comment]
Great! sorry for inconvenience 👻
