### ISSUE TITLE
A certain shader fails to compile

### ISSUE THREAD

**Issue by demicuz** [fand/veda#58]
[This is a fragment shader gist](https://gist.github.com/demicuz/e57a7a58f9c26d2f63b56c0cd27747eb) with the issue (VEDA 2.4.1). Atom editor freezes while compiling it. The exact same shader runs nicely in [The Book of Shaders editor](http://thebookofshaders.com/edit.php?log=180121214122) and on [ShaderToy](https://www.shadertoy.com/view/ll2fzK) (links contain the code).
[A newer version](https://www.shadertoy.com/view/lt2fDz) of this shader does run in VEDA.

**Comment by fand** [comment]
@demicuz 
I couldn't reproduce the bug... both revision of the code works quite well on my environment.
Do you see any errors if you open Devtools by `ctrl-alt-i` ?

![2018-01-25 20 38 10](https://user-images.githubusercontent.com/1403842/35386728-6e4691ea-0210-11e8-8074-82ab4066716f.png)
![2018-01-25 20 38 33](https://user-images.githubusercontent.com/1403842/35386684-497a1e4a-0210-11e8-9341-e1aa099d613d.png)

`pixelRate` and `frameskip` are just for performance.

**Comment by demicuz** [comment]
I've removed all the blank lines and it worked like a charm. See #57
