### ISSUE TITLE
server not working. dyld: Library not loaded

### ISSUE THREAD

**Issue by Chovin** [fand/veda#67]
trying to turn on a server with `"server": 1234` is giving `dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.59.dylib Referenced from: /usr/local/bin/node Reason: image not found`

**Comment by fand** [comment]
@Chovin 
hmm.. it seems that something's wrong with your Node.js
Is Node.js installed successfully? then how did you install it, by `brew`, by `nvm` ?

**Comment by Chovin** [comment]
I probably installed it via brew. did so awhile ago though. works after updating node. sorry!
