### ISSUE TITLE
Clarification for Installation instructions on website for glslangValidator on windows

### ISSUE THREAD

**Issue by MacroMachines** [fand/veda#75]
on the website instructions to install for windows, ti says to  put in the directory to glslangValidator, in the settings, I ended up having to put the filename also.   I suggest changing this:  
After that, add installed glslangValidator to your PATH environment variable.
In Windows, glslangValidator will be installed in C:\VulkanSDK\( version )\Bin.   
The path of glslangValidator can also be specified in the settings of VEDA  
C:\VulkanSDK\( version )\Bin\glslangValidator.exe<< add right here

**Comment by fand** [comment]
I've revised the page. https://veda.gl/install/
Thx @MacroMachines ! 😸
