### ISSUE TITLE
Keyboard input explination

### ISSUE THREAD

**Issue by MacroMachines** [fand/veda#82]
I tried the keyboard input example but there is no information as to how to get the keys to affect the shader rather than add a letter to the running shader at the cursor.
I suggest adding a blurb to the help / and a comment in the example
found this on the website https://veda.gl/features/keyboard/ which works great (z key not showing on osx chrome). the example does have the keyboard setting comment header.  if this is not possible in the atom editor that would be worth noting in the relevant help/package readme

**Comment by fand** [comment]
Well...keyboard input is mainly focused on usage with VEDA.js.
VEDA (for Atom) can't prevent keyboard input affecting the editing file on Atom.

Also, VEDA.js doesn't support header comments.
If you wanna use keyboard input in website, you have to call `veda.toggleKeyboard(true)` like this:
https://github.com/fand/veda.gl/blob/master/pages/features/keyboard.js#L19

**Comment by fand** [comment]
uh I forgot, VEDA now has fullscreen mode!
https://twitter.com/amagitakayosi/status/986257632909410304
I added the explanation to the doc: https://veda.gl/features/keyboard/
